apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      containers:
        - name: container1
          image: busybox
          command: ["/bin/sh", "-c", "while true; do echo 'Container 1 is running'; sleep 10; done"]
          volumeMounts:
            - name: shared-volume
              mountPath: /shared-data
        - name: container2
          image: nginx
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc

